version: '3.8'

services:
  app:
    build: .
    container_name: dat_ve_xe_khach
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/dat_ve_xe_khach
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: trung@123
     
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: trung@123
      MYSQL_DATABASE: dat_ve_xe_khach
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
